name: docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  actions: read

jobs:
  jupyter:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - run: brew install pandoc

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: pip install -r requirements.txt
    - run: pip install nb2plots

    - name: Convert notebook
      run: |
        cd utils
        jupyter nbconvert --to notebook --execute examples.ipynb
        nb2plots examples.nbconvert.ipynb > examples.rst

    - uses: actions/upload-artifact@v4
      with:
        name: examples.rst
        path: utils/examples.rst

  builddocs:
    needs: jupyter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v4
      with:
        name: examples.rst
        path: docs

    - uses: BrianJKoopman/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages

    - uses: geekyeggo/delete-artifact@v2
      with:
        name: examples.rst
